[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "6jDGSHbMBf4HXAmpcabQDDWgtfBDU45dD6KNZa3Y9a6T"
[programs.devnet]
nft_lend_borrow = "6jDGSHbMBf4HXAmpcabQDDWgtfBDU45dD6KNZa3Y9a6T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
